# Copyright (c) 2026 Harald Glab-Plhak. Licensed under the MIT License.
# GitHub Sponsors funding configuration for YATestEnvironment.
github: hglabplh_tech
custom:
  - "https://stripe.com"
  - "https://github.com/hglabplh-tech/YATestEnvironment"

