<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="https://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.clojars.hglabplh</groupId>
  <artifactId>YATestEnvironment</artifactId>
  <packaging>jar</packaging>
  <version>1.4-SNAPSHOT</version>
  <name>YATestEnvironment</name>
  <description>Clojure project to have a test Environment </description>
  <url>https://github.com/hglabplh-tech/YATestEnvironment.git</url>
  <licenses>
    <license>
      <name>MIT License</name>
      <url>https://mit-license.org</url>
    </license>
  </licenses>
  <scm>
    <url>https://github.com/hglabplh-tech/YATestEnvironment</url>
    <connection>scm:git:git://github.com/hglabplh-tech/YATestEnvironment.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/hglabplh-tech/YATestEnvironment.git</developerConnection>
    <tag>143bc97bd5fa1858b49c7751701fee4ec0a30ffd</tag>
  </scm>
  <build>
    <sourceDirectory>src/main/clojure</sourceDirectory>
    <testSourceDirectory>src/test/clojure</testSourceDirectory>
    <resources>
      <resource>
        <directory>src/test/resources</directory>
      </resource>
      <resource>
        <directory>lib/tools.jar</directory>
      </resource>
    </resources>
    <testResources>
      <testResource>
        <directory>src/test/resources</directory>
      </testResource>
      <testResource>
        <directory>lib/tools.jar</directory>
      </testResource>
    </testResources>
    <directory>target</directory>
    <outputDirectory>target/classes</outputDirectory>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>1.7</version>
        <executions>
          <execution>
            <id>add-source</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>src/main/java</source>
              </sources>
            </configuration>
          </execution>
          <execution>
            <id>add-test-source</id>
            <phase>generate-test-sources</phase>
            <goals>
              <goal>add-test-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>src/test/java</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <repositories>
    <repository>
      <id>central</id>
      <url>https://repo1.maven.org/maven2/</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
      </releases>
    </repository>
    <repository>
      <id>clojars</id>
      <url>https://repo.clojars.org/</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
      </releases>
    </repository>
    <repository>
      <id>java.net</id>
      <url>https://download.java.net/maven/2</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
      </releases>
    </repository>
    <repository>
      <id>jitpack</id>
      <url>https://jitpack.io</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
      </releases>
    </repository>
    <repository>
      <id>UniHildes</id>
      <url>https://projects.sse.uni-hildesheim.de/qm/maven</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
      </releases>
    </repository>
    <repository>
      <id>sonatype</id>
      <url>https://oss.sonatype.org/content/repositories/releases</url>
      <snapshots>
        <enabled>false</enabled>
        <updatePolicy>always</updatePolicy>
        <checksumPolicy>fail</checksumPolicy>
      </snapshots>
      <releases>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
        <checksumPolicy>fail</checksumPolicy>
      </releases>
    </repository>
  </repositories>
  <dependencyManagement>
    <dependencies/>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>clojure</artifactId>
      <version>1.12.3</version>
    </dependency>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>clojure-contrib</artifactId>
      <version>1.2.0</version>
    </dependency>
    <dependency>
      <groupId>lein-javadoc</groupId>
      <artifactId>lein-javadoc</artifactId>
      <version>0.3.0</version>
    </dependency>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>core.async</artifactId>
      <version>1.6.681</version>
    </dependency>
    <dependency>
      <groupId>de.active-group</groupId>
      <artifactId>active-clojure</artifactId>
      <version>0.45.1</version>
    </dependency>
    <dependency>
      <groupId>de.active-group</groupId>
      <artifactId>active-data</artifactId>
      <version>0.3.3</version>
    </dependency>
    <dependency>
      <groupId>com.github.technomancy</groupId>
      <artifactId>leiningen</artifactId>
      <version>2.11.2</version>
    </dependency>
    <dependency>
      <groupId>org.reflections</groupId>
      <artifactId>reflections</artifactId>
      <version>0.10.2</version>
    </dependency>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>data.json</artifactId>
      <version>2.5.1</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>5.9.1</version>
    </dependency>
    <dependency>
      <groupId>lein-asciidoctorj</groupId>
      <artifactId>lein-asciidoctorj</artifactId>
      <version>0.0.5</version>
    </dependency>
    <dependency>
      <groupId>jdk.tools</groupId>
      <artifactId>jdk.tools</artifactId>
      <version>1.7</version>
    </dependency>
    <dependency>
      <groupId>org.ninia</groupId>
      <artifactId>jep</artifactId>
      <version>4.3.1</version>
    </dependency>
  </dependencies>
  <developers>
    <developer>
      <id>hglabplh-tech</id>
      <name>Harald Glab-Plhak</name>
      <url>https://hglabplh-tech.github.io</url>
      <roles>
        <role>developer</role>
        <role>maintainer</role>
      </roles>
    </developer>
  </developers>
</project>

<!-- This file was autogenerated by Leiningen.
  Please do not edit it directly; instead edit project.clj and regenerate it.
  It should not be considered canonical data. For more information see
  https://codeberg.org/leiningen/leiningen -->
